dist: xenial
sudo: false

language: python
python:
  - "3.7"
  - "3.8"
  - "pypy3.7-7.3.2"

env:
  - CASS_DRIVER_NO_CYTHON=1

addons:
  apt:
    packages:
    - build-essential
    - python-dev
    - pypy-dev
    - libc-ares-dev
    - libev4
    - libev-dev

install:
  - pip install --upgrade pip setuptools
  - if [[ $TRAVIS_PYTHON_VERSION != "pypy3.7-7.3.2" ]]; then pip install --upgrade importlib-metadata; fi
  - pip install tox-travis
  - if [[ $TRAVIS_PYTHON_VERSION != "pypy3.7-7.3.2" ]]; then pip install lz4; fi

script:
  - tox
  - tox -e gevent_loop
  - tox -e eventlet_loop
